[targets]

localhost              ansible_connection=local             ansible_python_interpreter=/usr/bin/python
sealverin              ansible_user=almalinux
homelab                ansible_user=vpetukhov
